# 3:15
from tkinter import *
win = Tk()
win.title("Let's talk about the menu")
menubar = Menu(win)
File = Menu(menubar,tearoff=0)
# File.add_command(label = "New Text File")
subFile = Menu(File,tearoff=0)
subFile.add_command(label = "sub_1")
subFile.add_command(label = "sub_2")
File.add_cascade(menu = subFile, label="New Text File")
File.add_command(label = "New File")
File.add_separator()
File.add_command(label = "New Window")
menubar.add_cascade(menu = File , label = "File")
win.config(menu=menubar)

edit = Menu(menubar,tearoff=0)
edit.add_command(label = "Undo")
edit.add_command(label = "Redo")
edit.add_command(label = "Paste")
menubar.add_cascade(menu = edit , label = "Edit")
win.config(menu=menubar)
win.mainloop()